#!/bin/sh

#
# BSPWM CONFIG
# by unixkiwi
#

# WALLPAPER
~/.scripts/wall

# BSPWM CONFIGURATION
. "${HOME}/.cache/wal/colors.sh"

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d 10 11 12 13 14 15 16 17 18 19

bspc config focus_follows_pointer true # focus on hover

bspc config border_width 4 # border
bspc config window_gap 8 # gaps between windows

# border colors
bspc config focused_border_color "$foreground"
bspc config normal_border_color "$background"
bspc config active_border_color "$background"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# AUTOSTART
# cursor
xsetroot -cursor_name left_ptr

# keyboard layout
setxkbmap de

# Bluetooth
killall blueman-applet && blueman-applet &

# sxhkd keys
killall sxhkd
sxhkd &

# Bar & Compositor
~/.scripts/autostart

# Notifications
killall dunst
dunst &

# NetworkManager Tray
killall nm-applet
nm-applet &

# Clipboard Manager
killall copyq
copyq &
