#! /bin/sh

#
# BSPWM CONFIG
# by unixkiwi
#

# AUTOSTART
setxkbmap de

# Bluetooth
killall blueman-applet
blueman-applet &

# sxhkd keys
killall sxhkd
sxhkd &

# Wallpaper
killall nitrogen
nitrogen --restore # Wallpaper

# Bar
killall polybar
polybar top1; polybar top2 &

# Compositor
killall picom
picom &

# Notifications
killall dunst
dunst &

# BSPWM CONFIGURATION
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true # focus on hover

bspc config border_width 4 # border
bspc config window_gap 8 # gaps between windows

# border colors
bspc config focused_border_color "#98c379"
bspc config normal_border_color "#3e4452"
bspc config active_border_color "#e06c75"
bspc config presel_feedback_color "#56b6c2"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true


# WINDOW RULES
