#!/bin/bash

choice=$( echo "\n\n\n\n" | rofi -dmenu -i -theme $HOME/.config/rofi/powermenu.rasi )

case $choice in
    )
    systemctl poweroff
    ;;
  )
    systemctl reboot
    ;;
  )
    systemctl suspend
    ;;
   )
    i3lock -c 000000
    ;;
   )
    bspc quit
    ;;
esac
