#!/bin/bash

choice=$( echo "Poweroff\nReboot\nLogout\nLock\nSuspend" | rofi -dmenu -i -theme ~/.config/rofi/powermenu.rasi)

case $choice in
    Poweroff)
    systemctl poweroff
    ;;
  Reboot)
    systemctl reboot
    ;;
  Suspend)
    systemctl suspend
    ;;
   Lock)
    i3lock -c 000000
    ;;
   Logout)
    bspc quit
    ;;
esac
