#!/bin/bash

volume_icon="VOL"

function get_volume {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

function get_mute {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'
}

function send_notification {

    volume=$get_volume

    notify-send -t 2000 -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume "$volume_icon $volume%"

}
# notify-send -t $notification_timeout -h string:x-dunst-stack-tag:volume_notif -h int:value:$volume "$volume_icon $volume%"
send_notification